# This workflow is provided for reference only
# Manual deployment is preferred per user settings
# To use: Uncomment the workflow and configure secrets

# name: Deploy to Firebase Hosting
# 
# on:
#   push:
#     branches:
#       - main
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       
#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
#           channelId: live
#           projectId: aba-mastery-app

# Manual deployment command:
# firebase deploy --only hosting

